# Welcome to Jekyll!

# Website settings
title: "CodePig"
description: "Jack's blog,use Jekyll and github pages."
keywords: "xiuxingsang,swift,objective-c,react-native,github,jekyll"
baseurl: "/"
imageurl: "https://source.unsplash.com/category/nature/2600x500"
url: "https://xiuxingsang.github.io/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'CodePig'
  first_name: 'zhu'
  last_name: 'chen'
  cv: 'http://www.wsiyao.com'
  email: 'zhuchen3350@gmail.com'
  facebook_username: 'xiuxingsang'
  github_username: 'xiuxingsang'
  avatar: 'static/img/landing/Jack.jpg'
  desc: ' Hi,我是朱琛,一个前端开发工程师，12级计算机专业；两年实战开发经验，多款上架项目和[github](https://github.com/xiuxingsang)代存demo；有良好的面向对象编程思想,热爱编程。有一定的H5开发经验；有较强的学习能力，喜欢看技术方面的书籍不断扩充新知识；善于学习和运用新知识，思维敏捷，喜欢钻研，并将钻研的新知识总结归纳到笔记和上传到个人技术博客；有较强的责任心和一定的调试水平，对待事情力求完美，希望能写出优雅的代码。'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: CodePig
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
